//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.EnumResource", typeof(EnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string NEW_TYPE_NEWS {
            get {
                return ResourceManager.GetString("NEW_TYPE_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin khuyến mại.
        /// </summary>
        public static string NEW_TYPE_PROMOTION {
            get {
                return ResourceManager.GetString("NEW_TYPE_PROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu .
        /// </summary>
        public static string NOTIFICATION_TYPE_INTRO {
            get {
                return ResourceManager.GetString("NOTIFICATION_TYPE_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string NOTIFICATION_TYPE_ORDER {
            get {
                return ResourceManager.GetString("NOTIFICATION_TYPE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mại.
        /// </summary>
        public static string NOTIFICATION_TYPE_PROMOTION {
            get {
                return ResourceManager.GetString("NOTIFICATION_TYPE_PROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        public static string NOTIFICATION_TYPE_SYSTEM {
            get {
                return ResourceManager.GetString("NOTIFICATION_TYPE_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá đơn hàng.
        /// </summary>
        public static string PROMOTION_CONDITION_TYPE_ORDER {
            get {
                return ResourceManager.GetString("PROMOTION_CONDITION_TYPE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá phí vận chuyển.
        /// </summary>
        public static string PROMOTION_CONDITION_TYPE_SHIPPING {
            get {
                return ResourceManager.GetString("PROMOTION_CONDITION_TYPE_SHIPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá trực tiếp vào sản phẩm.
        /// </summary>
        public static string PROMOTION_DISCOUNT_TYPE_PRODUCT {
            get {
                return ResourceManager.GetString("PROMOTION_DISCOUNT_TYPE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát hành voucher.
        /// </summary>
        public static string PROMOTION_DISCOUNT_TYPE_VOUCHER {
            get {
                return ResourceManager.GetString("PROMOTION_DISCOUNT_TYPE_VOUCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá theo phần trăm.
        /// </summary>
        public static string PROMOTION_TYPE_PERCENT {
            get {
                return ResourceManager.GetString("PROMOTION_TYPE_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá theo số tiền cụ thể.
        /// </summary>
        public static string PROMOTION_TYPE_PRICE {
            get {
                return ResourceManager.GetString("PROMOTION_TYPE_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string STATUS_ACTIVE {
            get {
                return ResourceManager.GetString("STATUS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ.
        /// </summary>
        public static string STATUS_CANCEL {
            get {
                return ResourceManager.GetString("STATUS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        public static string STATUS_FINISH {
            get {
                return ResourceManager.GetString("STATUS_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ duyệt.
        /// </summary>
        public static string STATUS_INACTIVE {
            get {
                return ResourceManager.GetString("STATUS_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị.
        /// </summary>
        public static string USER_TYPE_ADMIN {
            get {
                return ResourceManager.GetString("USER_TYPE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        public static string USER_TYPE_AGENCY {
            get {
                return ResourceManager.GetString("USER_TYPE_AGENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string USER_TYPE_CUSTOMER {
            get {
                return ResourceManager.GetString("USER_TYPE_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string USER_TYPE_EMPLOYEE {
            get {
                return ResourceManager.GetString("USER_TYPE_EMPLOYEE", resourceCulture);
            }
        }
    }
}
