//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá.
        /// </summary>
        public static string ACTION_DELETE {
            get {
                return ResourceManager.GetString("ACTION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string ACTION_INSERT {
            get {
                return ResourceManager.GetString("ACTION_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string ACTION_UPDATE {
            get {
                return ResourceManager.GetString("ACTION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string ACTION_VIEW {
            get {
                return ResourceManager.GetString("ACTION_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string F_ACCOUNT {
            get {
                return ResourceManager.GetString("F_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string F_CODE {
            get {
                return ResourceManager.GetString("F_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khiếu nại.
        /// </summary>
        public static string F_COMPLAIN {
            get {
                return ResourceManager.GetString("F_COMPLAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu.
        /// </summary>
        public static string F_DATA {
            get {
                return ResourceManager.GetString("F_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vận chuyển.
        /// </summary>
        public static string F_DATE_TRANSPORT {
            get {
                return ResourceManager.GetString("F_DATE_TRANSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string F_DISTRICT {
            get {
                return ResourceManager.GetString("F_DISTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        public static string F_EXPIRE_DATE {
            get {
                return ResourceManager.GetString("F_EXPIRE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Sale.
        /// </summary>
        public static string F_FLASH_SALE {
            get {
                return ResourceManager.GetString("F_FLASH_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều cao.
        /// </summary>
        public static string F_HEIGHT {
            get {
                return ResourceManager.GetString("F_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string F_LOGIN {
            get {
                return ResourceManager.GetString("F_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string F_LOGOUT {
            get {
                return ResourceManager.GetString("F_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều rộng.
        /// </summary>
        public static string F_LONGS {
            get {
                return ResourceManager.GetString("F_LONGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string F_NAME {
            get {
                return ResourceManager.GetString("F_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string F_NEWS {
            get {
                return ResourceManager.GetString("F_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string F_NOTIFICATION {
            get {
                return ResourceManager.GetString("F_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string F_ORDER {
            get {
                return ResourceManager.GetString("F_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        public static string F_OTP {
            get {
                return ResourceManager.GetString("F_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiện hàng.
        /// </summary>
        public static string F_PACKAGE {
            get {
                return ResourceManager.GetString("F_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string F_PASSWORD {
            get {
                return ResourceManager.GetString("F_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string F_PASSWORD_NEW {
            get {
                return ResourceManager.GetString("F_PASSWORD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string F_PHONE {
            get {
                return ResourceManager.GetString("F_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string F_PRODUCT {
            get {
                return ResourceManager.GetString("F_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string F_PRODUCT_CATEGORY {
            get {
                return ResourceManager.GetString("F_PRODUCT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm cha.
        /// </summary>
        public static string F_PRODUCT_CATEGORY_PARENT {
            get {
                return ResourceManager.GetString("F_PRODUCT_CATEGORY_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình khuyến mại.
        /// </summary>
        public static string F_PROMOTION {
            get {
                return ResourceManager.GetString("F_PROMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/TP.
        /// </summary>
        public static string F_PROVINCE {
            get {
                return ResourceManager.GetString("F_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạng mức tài khoản.
        /// </summary>
        public static string F_RANK {
            get {
                return ResourceManager.GetString("F_RANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string F_RE_PASSWORD {
            get {
                return ResourceManager.GetString("F_RE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi làm mới token.
        /// </summary>
        public static string F_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("F_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền truy cập.
        /// </summary>
        public static string F_ROLE {
            get {
                return ResourceManager.GetString("F_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string F_SLIDER {
            get {
                return ResourceManager.GetString("F_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        public static string F_START_DATE {
            get {
                return ResourceManager.GetString("F_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string F_STATUS {
            get {
                return ResourceManager.GetString("F_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string F_TOKEN {
            get {
                return ResourceManager.GetString("F_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string F_TOTAL {
            get {
                return ResourceManager.GetString("F_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu.
        /// </summary>
        public static string F_TYPE {
            get {
                return ResourceManager.GetString("F_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string F_UNITS {
            get {
                return ResourceManager.GetString("F_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string F_USER {
            get {
                return ResourceManager.GetString("F_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string F_USER_NAME {
            get {
                return ResourceManager.GetString("F_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string F_USERNAME {
            get {
                return ResourceManager.GetString("F_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        public static string F_VALUE {
            get {
                return ResourceManager.GetString("F_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giảm giá.
        /// </summary>
        public static string F_VOUCHER {
            get {
                return ResourceManager.GetString("F_VOUCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường/Xã.
        /// </summary>
        public static string F_WARD {
            get {
                return ResourceManager.GetString("F_WARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng.
        /// </summary>
        public static string F_WEIGHT {
            get {
                return ResourceManager.GetString("F_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài .
        /// </summary>
        public static string F_WIDTH {
            get {
                return ResourceManager.GetString("F_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi khi truy cập dữ liệu.
        /// </summary>
        public static string MSG_DB {
            get {
                return ResourceManager.GetString("MSG_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không trùng khớp với {1}.
        /// </summary>
        public static string MSG_DUPLICATE {
            get {
                return ResourceManager.GetString("MSG_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trắng.
        /// </summary>
        public static string MSG_EMPTY {
            get {
                return ResourceManager.GetString("MSG_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi không mong muốn. Vui lòng liên hệ lại quản trị hoặc thử lại sau.
        /// </summary>
        public static string MSG_EXCEPTION {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại.
        /// </summary>
        public static string MSG_EXISTS {
            get {
                return ResourceManager.GetString("MSG_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã hết hạn.
        /// </summary>
        public static string MSG_EXPIRE {
            get {
                return ResourceManager.GetString("MSG_EXPIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  thất bại.
        /// </summary>
        public static string MSG_FAILED {
            get {
                return ResourceManager.GetString("MSG_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng.
        /// </summary>
        public static string MSG_FORMAT {
            get {
                return ResourceManager.GetString("MSG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không chính xác.
        /// </summary>
        public static string MSG_INCORRECT {
            get {
                return ResourceManager.GetString("MSG_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không hợp lệ.
        /// </summary>
        public static string MSG_INVALID {
            get {
                return ResourceManager.GetString("MSG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token chưa hết hạn.
        /// </summary>
        public static string MSG_JWT_NOT_EXPIRE {
            get {
                return ResourceManager.GetString("MSG_JWT_NOT_EXPIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản hoặc mật khẩu không đúng. Vui lòng kiểm tra lại.
        /// </summary>
        public static string MSG_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("MSG_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chưa được kích hoạt.
        /// </summary>
        public static string MSG_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("MSG_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0}.
        /// </summary>
        public static string MSG_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập.
        /// </summary>
        public static string MSG_PERMISSION {
            get {
                return ResourceManager.GetString("MSG_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống.
        /// </summary>
        public static string MSG_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã bị huỷ hoặc thu hồi.
        /// </summary>
        public static string MSG_REVOKE {
            get {
                return ResourceManager.GetString("MSG_REVOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thành công.
        /// </summary>
        public static string MSG_SUCESS {
            get {
                return ResourceManager.GetString("MSG_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu lớn hơn thời gian kết thúc.
        /// </summary>
        public static string MSG_TIME_START_MORE_THAN_TIME_END {
            get {
                return ResourceManager.GetString("MSG_TIME_START_MORE_THAN_TIME_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã được sử dụng.
        /// </summary>
        public static string MSG_USED {
            get {
                return ResourceManager.GetString("MSG_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được kích hoạt thông tin. Vui lòng sử dụng chức năng này khi được quyền truy cập.
        /// </summary>
        public static string MSG_USER_NOT_UPDATE {
            get {
                return ResourceManager.GetString("MSG_USER_NOT_UPDATE", resourceCulture);
            }
        }
    }
}
